apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-clusterip
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.app.components }}    
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}        
    