
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include "chart.labels" . | indent 4}}
data:  
  name: {{ .Values.name | upper | quote}}
  {{- if eq .Values.env "production" }}
  paymentToken: "1234"
  {{- else if eq .Values.env "test" }}
  paymentToken: "9876"
  {{- end }} 
  {{- with .Values.value.requirements.limits }}
  memory: {{ .memory }}
  cpu: {{ .cpu }}
  version: {{ $.Values.app.version }}
  {{- end }}
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
  users: 
    {{- range tuple "Anton" "Vasia" }}
    - {{ . }}
    {{- end }}