apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template: 
    metadata: 
      labels:
        components: backend
    spec:
      containers:
        - name: short-api
          image: antonlarichev/short-api:v1.0
          env:
          - name: DATABASE_URL
            value: "postgresql://demo:demo@postgres-clusterip:5432/demo"
          ports:
            - containerPort: 3000          
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"